version: "3.9"
services:
  postgres:
    container_name: user-stargres
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5433"
    expose:
      - "5433"