version: "3.9"
services:

  user-service:
    container_name: user-service
    build:
      dockerfile: user-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: user-stargres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - "5432"