server:
  port: 8081

spring:

  application:
    name: user-service
    url:
      user: /public/api/v1/users/
      image: /public/api/v1/images/
      friend-request: /public/api/v1/users/{userId}/friend-requests/
      friendship: /public/api/v1/users/{userId}/friendships/

  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          keycloack:
            client-id: user-api
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloack:
            issuer-uri: http://localhost:8080/realms/UserServiceKeycloack
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/UserServiceKeycloack
